learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
"""Определение схемы url для приложения learning_logs"""
from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
        #Домашняя страница
    path('', views.index, name = 'index'),
        #страница со списком всех тем
    path('topics/', views.topics, name = 'topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
        #страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    # path('index2/', views.index2, name='index2'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    path('delete_topic/<int:topic_id>', views.delete_topic, name='delete_topic'),
    path('delete_entry/<int:entry_id>', views.delete_entry, name='delete_entry'),
    
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
        # Включить url авторизации по умолчанию
    path('', include('django.contrib.auth.urls')),
    #   Страница регистрации
    path('register/', views.register, name='register'),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """информация полученная пользователем по теме"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField(max_length=10000)
    date_added = models.DateTimeField(auto_now_add=True)
    # owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'



    def __str__(self):
        """возвращает строковое представление модели"""
        length_text = len(self.text)
        if length_text > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Создайте запись'}
        widgets = {'text': forms.Textarea(attrs={'cols': 500, 'placeholder': 'Введите текст'})}


class EditForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Редактируйте запись'}
        widgets = {'text': forms.Textarea(attrs={'cols': 500, 'placeholder': 'Введите текст'})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.http import HttpResponseNotFound

from .models import Topic, Entry
from .forms import TopicForm, EntryForm, EditForm
from django.http import Http404

# Здесь представлены представления


def index(request):
    """Домашняя страница приложения learning_log"""
    return render(request, 'learning_logs/index.html')


def check_topic_owner(topic, request):
    """Проверка того, что тема принадлежит текущему пользователю"""
    if topic.owner != request.user:
        raise Http404


def check_entry_owner(entry, request):
    """Проверка того, что тема принадлежит текущему пользователю"""
    if entry.owner != request.user:
        raise Http404


@login_required
def topics(request):
    """выводит список тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """выводит одну тему и все ее записи"""
    topic = get_object_or_404(Topic, id=topic_id)
    # Проверка того, что тема принадлежит текущему пользователю
    # if topic.owner != request.user:
    #     raise Http404
    check_topic_owner(topic, request)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """определяет новую тему"""
    if request.method != 'POST':
        #данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
        #отправлены данные POST; обработать данные.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    #вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """добавляет новую запись по конкретной теме"""
    topic = get_object_or_404(Topic, id=topic_id)
    check_topic_owner(topic, request)
    if request.method != 'POST':
        #данные не отправлялиссь, создается пустая форма
        form = EntryForm()
    else:
        #данные отправлены, обработать данные
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return redirect('learning_logs:topic',topic_id=topic_id)

    #вывести пустую или недействительную форму
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """редактирует существующую запись"""
    entry = get_object_or_404(Entry, id=entry_id)
    topic = entry.topic
    # Проверка того, что тема принадлежит текущему пользователю
    check_topic_owner(topic, request)
    # check_entry_owner(entry, request)
    if request.method != 'POST':
        #Исходный запрос; форма заполняется данными текущей запсиси.
        form = EditForm(instance=entry)
    else:
        #отправка данных POST; обработать данные.
        form = EditForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def delete_topic(request, topic_id):
    """удаляет тему"""
    try:
        topic = Topic.objects.get(id=topic_id)
        context = {'topic': topic}
        check_topic_owner(topic, request)
        topic.delete()
        return HttpResponseRedirect("/topics")

    except Topic.DoesNotExist:
        return HttpResponseNotFound("<h2>Тема не найдена</h2>")


def delete_entry(request, entry_id):
    """удаляет запись"""
    try:
        entry = Entry.objects.get(id=entry_id)
        topic = entry.topic
        context = {'entry': entry}
        check_topic_owner(topic, request)
        entry.delete()
        return redirect('learning_logs:topic', topic_id=topic.id)

    except Topic.DoesNotExist:
        return HttpResponseNotFound("<h2>Запись не найдена</h2>")

users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """регистрирует нового пользователя"""
    if request.method != 'POST':
        # Выводит пустую форму регистрации
        form = UserCreationForm()
    else:
        # Обработка заполненной формы
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу
            login(request, new_user)
            return redirect('learning_logs:index')

    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Журнал обучения</title>
    {% bootstrap_css %}
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand">Журнал обучения</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expended="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">

            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <span class="navbar-text">Привет, {{user.username}}!</span>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>
    </main>
    <footer>

    </footer>
  {% bootstrap_javascript jquery='full' %}
  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block content %}
<p><a class="btn btn-primary" href="{% url 'learning_logs:topic' topic.id %}">Назад</a></p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='POST'>
  {% csrf_token %}
  {% bootstrap_form form %}
  <button name="submit" class="btn btn-primary">Сохранить изменения</button>
</form>
{% endblock %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Отслеживайте свое обучение.</h1>

    <p class="lead">
      Создайте свой собственный журнал обучения и ведите список тем, которые вы
       изучаете. Всякий раз, когда вы узнаете что-то новое о теме, сделайте
       запись, обобщающую то, что вы узнали.
    </p>
    {% if user.is_authenticated %}
      <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}" role="button">Начать</a>
    {% else %}
      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Зарегистрироваться</a>
      <br><br>
      <a class="btn btn-lg btn-primary" href="{% url 'users:login' %}" role="button">Войти</a>
    {% endif %}

  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap4 %}
{% block page_header %}
  <p><a href="{% url 'learning_logs:topic' topic.id %}" class="btn btn-primary">Назад</a></p>
{% endblock page_header %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="align-self-center">
        <form method="post" action="{% url 'learning_logs:new_entry' topic.id %}" class="form">
          {% csrf_token %}
          {% bootstrap_form form %}
          <button name="submit" class="btn btn-primary">Добавить</button>
          <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block content %}
<a class="btn btn-primary" href="{% url 'learning_logs:topics' %}">Назад</a>
<br><br><br>
<h3>Создайте тему:</h3>
<form class="col-5" action="{% url 'learning_logs:new_topic' %}" method='POST'>
  {% csrf_token %}
  {% bootstrap_form form %}
  <button name="submit" class="btn btn-primary">Создать тему</button>
</form>
{% endblock %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}


{% block page_header %}
  <a class="btn btn-primary" href="{% url 'learning_logs:topics' %}">Назад</a>
  <h1 class="text-center">{{ topic }}</h1>
{% endblock page_header %}
{% block content %}
<div class="row justify-content-center">
  <a href="{% url 'learning_logs:new_entry' topic.id %}" class="btn btn-primary">Добавить новую запись</a>
</div>
      <br><br>
      {% for entry in entries %}
      <div class="justify-content-center">
          <div class="card text">
            <div class="card-header">
              {{ entry.date_added|date:'M d, Y H:i' }}
            </div>
            <div class="card-body">
              <p class="card-text">{{ entry.text|linebreaks }}</p>
            </div>
              <div class="card-footer text-muted">
                <a href="{% url 'learning_logs:edit_entry' entry.id %}" class="btn btn-outline-success">Редактировать запись</a>
                <a href="{% url 'learning_logs:delete_entry' entry.id %}" class="btn btn-outline-danger">Удалить запись</a>
              </div>
          </div>
      </div>
      <br><br>
      {% empty %}
          <p>Здесь пока не создано ни одной записи.</p>
      {% endfor %}
{% endblock %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block content %}
    <h1>Темы</h1>
    <a class="btn btn-primary" href="{% url 'learning_logs:new_topic' %}">Добавить новую тему</a>
    <br>
    <br>
    <div class="list-group">
      <div class="container">
        {% for topic in topics %}
        <div class="row">
          <div class="col">
            <a class="list-group-item list-group-item-action" href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
          </div>
          <div class="col">
            <a href="{% url 'learning_logs:delete_topic' topic.id %}" class="btn btn-outline-danger">Удалить</a>
          </div>
        </div>
        <br>
        {% empty %}
        <li>Пока не создано ни одной темы</li>
        {% endfor %}
    </div>

{% endblock %}